### ISSUE TITLE
Clean up column names and column order for xlsx outputs

### ISSUE THREAD

**Issue by rmichie** [DEQcdonald/st_report_files#1]
Low Priority

To make things a little more friendly and clean for the final report I think we need to clean up the column names and change the order of the columns for the xlsx outputs that happen in the code [here](https://github.com/donco/st_report_files/blob/master/state_param_summary2.R#L324-L328).

Here are my suggested final column names and ordering:

summary_by_station

| Station ID | Station Name | Subbasin Name | HUC8 | Assessment Unit ID | Latitude | Longitude | Parameter | Sampling Organizations | Status 1999-2002 | Status 2003-2006 | Status 2007-2010 | Status 2011-2014 | Status 2015-2018 | Trend |
| -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- |

summary_by_AU - Note: can we summarize all the Station IDs that contributed data to that AU for that parameter as well as Sampling Orgs?

| Assessment Unit ID | Assessment Unit Name | Subbasin Name | HUC8 | Parameter | Station IDs | Sampling Organizations | Status 1999-2002 | Status 2003-2006 | Status 2007-2010 | Status 2011-2014 | Status 2015-2018 |
| -- | -- | -- | -- | -- | -- | -- | -- | -- | -- |  -- | -- |

**Comment by DEQcdonald** [comment]
Addressed in commit 6deb60655400ff4c794a0bc75b9802985b61576a
