### ISSUE TITLE
Reference IR Methodology

### ISSUE THREAD

**Issue by DEQrmichie** [DEQcdonald/st_report_files#21]
The WQST Report should include a brief narrative and a reference to the IR methodology ([DEQ 2020][1]) since these are the methods we use to determine status.

I'm open to suggestions but it seems the logical place to have this narrative might be in the Water Quality Status Assessment section.

[1]: https://www.oregon.gov/deq/wq/Documents/irMethodologyF1820.pdf

**Comment by DEQrmichie** [comment]
I just noticed the draft word version of the report has the following language included in section 3.4 but it's not in the Rmarkdown?? Strange. This language works for me so can you start with adding this.

"We used the 2018/2020 Integrated Report assessment methodology (DEQ 2020) to determine attainment within each status period. The methodology considers all the applicable criteria for each parameter as well as the number of excursions for attainment conclusions. The specific methodology for each status category are described for each parameter in the sections below."

**Comment by DEQygrund** [comment]
It is strange. It has been added to the Rmarkdown file that will be merged to the master after the other issues are resolved.
