### ISSUE TITLE
Subbasin station status summary bar charts have wrong caption.

### ISSUE THREAD

**Issue by DEQrmichie** [DEQcdonald/st_report_files#25]
All the subbasin AU - paramater status bar charts have the wrong caption. It's the same caption as the station bar charts one figure up.

As an example see figure 46 on page 87 of the draft report. It has the same caption as figure 46 on page 86. 

This is probably happening because the captioner code has the same name.  Also see issue #26 about improving the caption.

**Comment by DEQrmichie** [comment]
Note I edited this issue from the original. I realized this is related to the bug in the captioner code rather than the caption wording. I made a new issue to address the caption wording. See #26 .

**Comment by DEQygrund** [comment]
Colin has suggested to change the the chunk options fig.cap to cap_list[[1]] and cap_list[[2]] in the AU and the Station code chunks. The codes have been updated in "state_sbubasin_summary.Rmd" and the markdown file has been merged to the master.
