### ISSUE TITLE
Columbia River maps include WQ limited streams outside of assessment area

### ISSUE THREAD

**Issue by rmichie** [DEQcdonald/st_report_files#6]
The parameter maps for the Columbia River show a number of water quality limited streams for areas adjacent to the Columbia River.  Only impairments on the Columbia River should be shown.

**Comment by DEQrmichie** [comment]
Closed. This issue has been moved to [#27 in odeqstatusandtrends][1].

[1]:https://github.com/DEQcdonald/odeqstatusandtrends/issues/27#issue-652917252
